trigger:
  - main
  # paths:
  #   include:
  #     - docker

pr:
  - main

resources:
  - repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: "442ea973-c852-4792-aa09-fab4a9df791f"

  imageRepository: "dataloader_benchmark"
  containerRegistry: "commondockerimages.azurecr.io"

  dockerfilecondaPath: "$(Build.SourcesDirectory)/docker/Dockerfile_base_conda"
  tagCurrentConda: "$(Build.SourceBranchName)_$(Build.BuildNumber)-conda"
  tagLatestConda: "latest-conda"
  tagLatest: "latest"

  # Agent VM image name
  vmImageName: "ubuntu-latest"

  # docker image names for pytest
  docker_base_azureml: $(containerRegistry)/$(imageRepository):$(tag_conda)

stages:
  # docs: https://docs.microsoft.com/azure/devops/pipelines/languages/docker
  - stage: BuildDockerImagesAndRunPytest
    displayName: Build docker; run pytests on built images
    jobs:
      - job: BuildDockerAzureMLBaseAndConda
        displayName: docker build azureml base; run pytest
        pool:
          vmImage: $(vmImageName)

        steps:
          - bash: |
              github_organization_prefix="AutonomousSystemsResearch/"
              full_repo_name=$(Build.Repository.Name)
              repo_name=${full_repo_name#"$github_organization_prefix"}
              git_short_hash_wrong=`git rev-parse --short=7 HEAD`  ## At least 7 digits, more if needed for uniqueness
              echo ""
              echo "full repo name:  $(Build.Repository.Name)"
              echo "repo name:  $repo_name"
              echo "Build Id:  $(Build.BuildId)"
              echo "Build BuildNumber:  $(Build.BuildNumber)"
              echo "Build Reason:  $(Build.Reason)"
              echo "Build Branch Name:  $(Build.SourceBranchName)"
              echo "PullRequest.SourceBranch: $(System.PullRequest.SourceBranch)"
              echo "PullRequestNumber: $(System.PullRequest.PullRequestNumber)"
              echo "PullRequestId: $(System.PullRequest.PullRequestId)"
              echo "Build.SourceVersion git hash (wrong):  $(Build.SourceVersion)"
              echo "System.PullRequest.SourceCommitId (right): $(System.PullRequest.SourceCommitId)"
              echo "Git commit message: $(Build.SourceVersionMessage)"
              echo "Short git hash wrong: $git_short_hash_wrong"
              git_hash=$(System.PullRequest.SourceCommitId):0:7
              git_short_hash=${git_hash:0:7}
              pr_number=$(System.PullRequest.PullRequestNumber)
              echo "Short git hash : $git_short_hash"
              echo "##vso[task.setvariable variable=repo_name]$repo_name"
              pr_number_git_commit_tag=PR-$pr_number-$git_short_hash-conda
              pr_number_latest_tag=PR-$pr_number-latest-conda
              echo "##vso[task.setvariable variable=tagPRCurrentCondaGitCommitHash]$pr_number_git_commit_tag"
              echo "##vso[task.setvariable variable=tagPRCurrentCondaLatest]$pr_number_latest_tag"
            workingDirectory: $(Build.SourcesDirectory)
            displayName: Print git info

          - bash: |
              echo "tagPRCurrentCondaGitCommitHash: $(tagPRCurrentCondaGitCommitHash)"
              echo "tagPRCurrentCondaLatest: $(tagPRCurrentCondaLatest)"
            workingDirectory: $(Build.SourcesDirectory)
            displayName: Print docker tags for PR

          - task: Docker@2
            displayName: Build and Push Image
            inputs:
              command: buildAndPush
              repository: $(imageRepository)
              dockerfile: $(dockerfilecondaPath)
              containerRegistry: $(dockerRegistryServiceConnection)
              ${{ if eq(variables['Build.SourceBranchName'], 'merge') }}:
                tags: |
                  $(tagPRCurrentCondaGitCommitHash)
                  $(tagPRCurrentCondaLatest)

              ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:
                tags: |
                  $(tagCurrentConda)
                  $(tagLatestConda)
                  $(tagLatest)

          # - bash: |
          #     docker run -d -i --name testapp -v $(Build.SourcesDirectory):/workdir -w /workdir $(containerRegistry)/$(imageRepository):$(tagCurrentConda)
          #   displayName: Run docker container

          # - script: |
          #     docker exec testapp bash -c "pip install -e .; pytest tests/test_dev_fast_run.py -k test_fast_dev_run_cpu"
          #   displayName: Run Pytest on Current Build
