description: dataloader-benchmark-dali

target:
  service: aml
  name: V100-1x-ded

environment:
  registry: commondockerimages.azurecr.io
  username: commondockerimages
  image: dataloader-benchmark:latest
  setup:
    - pip install --extra-index-url https://developer.download.nvidia.com/compute/redist --upgrade nvidia-dali-cuda110
    - pip install -e .

# $CONFIG_DIR is expanded to the directory of this config file.
code:
  local_dir: $CONFIG_DIR/../

storage:
  data:
    storage_account_name: commondatasets2
    container_name: commondatasets
    mount_dir: /mnt/data
    mount_options: ["--file-cache-timeout-in-seconds=0"]
  custom_output:
    storage_account_name: ramadaanaml
    container_name: mmvmae-benchmark-results
    mount_dir: /mnt/data_output
    is_output: True

jobs:
  - name: tartanair_dali_modalities_image_left_seq_len_1
    sku: G1
    command:
      - python src/benchmarks/azure_monitor.py &
      - python src/benchmarks/tartanair_dali.py
        --batch_size 64
        --image_dir /mnt/data/tartanair-release1-dali/abandonedfactory/Easy/P000/
        --is_amlt yes
    submit_args:
      container_args:
        shm_size: 640g
      env: { AZUREML_COMPUTE_USE_COMMON_RUNTIME: True }

  - name: tartanair_dali_modalities_image_left_seq_len_16
    sku: G1
    command:
      - python src/benchmarks/azure_monitor.py &
      - python src/benchmarks/tartanair_dali_sequence.py
        --batch_size 64
        --sequence_length 16
        --seq_dir /mnt/data/tartanair-release1-dali/abandonedfactory/Easy/P000/sequence_dali
        --is_amlt yes
    submit_args:
      container_args:
        shm_size: 640g
      env: { AZUREML_COMPUTE_USE_COMMON_RUNTIME: True }

  - name: tartanair_dali_modalities_depth_left_seq_len_1
    sku: G1
    command:
      - python src/benchmarks/azure_monitor.py &
      - python src/benchmarks/tartanair_dali_npy.py
        --batch_size 64
        --is_amlt yes
        --image_dir /mnt/data/tartanair-release1/abandonedfactory/Easy/P000/depth_left/
    submit_args:
      container_args:
        shm_size: 640g
      env: { AZUREML_COMPUTE_USE_COMMON_RUNTIME: True }

  # - name: tartanair_dali_modalities_rgb_separate_dir
  #   sku: G1
  #   command:
  #     - python src/benchmarks/azure_monitor.py &
  #     - python src/benchmarks/tartanair_dali.py
  #       --batch_size 64
  #       --image_dir /mnt/data/tartanair-release1-dali/abandonedfactory/Easy/P000/
  #       --is_amlt yes
  #   submit_args:
  #     container_args:
  #       shm_size: 640g
  #     env: { AZUREML_COMPUTE_USE_COMMON_RUNTIME: True }

  # - name: tartanair_dali_modalities_npy_depth_separate_dir
  #   sku: G1
  #   command:
  #     - python src/benchmarks/azure_monitor.py &
  #     - python src/benchmarks/tartanair_dali_npy.py
  #       --batch_size 64
  #       --is_amlt yes
  #       --image_dir /mnt/data/tartanair-release1-dali/abandonedfactory/Easy/P000/depth_left/
  #   submit_args:
  #     container_args:
  #       shm_size: 640g
  #     env: { AZUREML_COMPUTE_USE_COMMON_RUNTIME: True }
