description: dataloader-benchmark

target:
  service: aml
  name: v100-1x

environment:
  registry: commondockerimages.azurecr.io
  username: commondockerimages
  image: dataloader-benchmark:latest-ffcv
  setup:
    - pip install mlflow azureml-mlflow azureml-core
    - pip install -e .

# $CONFIG_DIR is expanded to the directory of this config file.
code:
  local_dir: $CONFIG_DIR/../

storage:
  data:
    storage_account_name: commondatasets2
    container_name: commondatasets
    mount_dir: /mnt/data
    mount_options: ["--file-cache-timeout-in-seconds=0"]
  results:
    storage_account_name: shuhangchen 
    container_name: amulet
    is_output: True

jobs:
  - name: tartanair_ffcv
    sku: 1xG1
    command:
      - export MKL_THREADING_LAYER="GNU"
      - python src/system_monitor.py --watch_every_n_seconds 1 &
      - python src/benchmarks/tartanair/tartanair_ffcv.py
        --dataset tartanair
        --benchmark_results_file /mnt/results/tartanair_ffcv.csv
        --beton_file /mnt/data/tartanair-release1/tartan_abandonedfactory_easy.beton
        --batch_size 32
        --num_workers 4
        --order quasi_random
        --os_cache False
    submit_args:
      container_args:
        shm_size: 640g