description: dataloader-benchmark

target:
  service: aml
  name: v100-1x

environment:
  registry: commondockerimages.azurecr.io
  username: commondockerimages
  image: dataloader-benchmark:latest
  setup:
    - pip install -e .

# $CONFIG_DIR is expanded to the directory of this config file.
code:
  local_dir: $CONFIG_DIR/../

storage:
  data:
    storage_account_name: commondatasets2
    container_name: commondatasets
    mount_dir: /mnt/data
    mount_options: ["--file-cache-timeout-in-seconds=0"]
  results:
    storage_account_name: shuhangchen
    container_name: amulet 
    is_output: True

jobs:
  - name: tartanair_og
    sku: 1xG1    
    submit_args:
      container_args:
        shm_size: 640g
    command:
      - python src/system_monitor.py --watch_every_n_seconds 1 &
      - python src/benchmarks/tartanair/tartanair_og.py
        --train_ann_file /mnt/data/tartanair-release1/train_ann_debug_ratnesh.json
        --benchmark_results_file /mnt/results/tartanair.csv
        --batch_size 32
        --num_workers 4
        --num_seq 1
        --modalities image_left depth_left flow_flow flow_mask seg_left 
        --seq_len 16
        --train_transform TartanAirNoTransform



