description: dataloader-benchmark

target:
  service: aml
  name: v100-1x

environment:
  registry: commondockerimages.azurecr.io
  username: commondockerimages
  image: dataloader-benchmark:latest
  setup:
    - pip install -e .

# $CONFIG_DIR is expanded to the directory of this config file.
code:
  local_dir: $CONFIG_DIR/../

storage:
  data:
    storage_account_name: commondatasets2
    container_name: commondatasets
    mount_dir: /mnt/data
    mount_options: ["--file-cache-timeout-in-seconds=0"]
  results:
    storage_account_name: shuhangchen
    container_name: amulet
    is_output: True

jobs:
  - name: tartanair_seqrecord
    sku: 1xG1
    command:
      - python src/benchmarks/seqrecord/tartan_record.py
    submit_args:
      container_args:
        shm_size: 640g
      env: { AZUREML_COMPUTE_USE_COMMON_RUNTIME: True }
