seed_everything: 42

# ---------------------------- TRAINER -------------------------------------------
trainer:
  default_root_dir: ${oc.env:AMLT_OUTPUT_DIR,/mnt/climate_pretraining/outputs/vit}

  precision: 16

  gpus: null
  num_nodes: 1
  accelerator: gpu
  strategy: ddp_find_unused_parameters_false

  min_epochs: 1
  max_epochs: 20
  enable_progress_bar: true

  sync_batchnorm: True
  enable_checkpointing: True
  resume_from_checkpoint: null

  # debugging
  fast_dev_run: false

  logger:
    class_path: pytorch_lightning.loggers.tensorboard.TensorBoardLogger
    init_args:
      save_dir: ${trainer.default_root_dir}/logs
      name: null
      version: null
      log_graph: False
      default_hp_metric: True
      prefix: ""

  callbacks:

    - class_path: pytorch_lightning.callbacks.RichModelSummary
      init_args:
        max_depth: -1

    - class_path: pytorch_lightning.callbacks.RichProgressBar

# ---------------------------- MODEL -------------------------------------------
model:
  lr: 0.0005
  weight_decay: 0.005

  net:
    class_path: src.models.components.linear.Linear
    init_args:
      img_size: [32, 64]
      in_channels: 2
      out_channels: 2

# ---------------------------- DATA -------------------------------------------
data:
  root_dir: /datadrive/datasets/5.625deg_equally_np
  reader: npy # npy or zarr
  dataset_type: forecast # pretrain or forecast (finetune)
  variables: ["z_500", "t_850"]
  predict_range: 6
  skip_steps: 1
  predict_steps: 4
  pct_train: 1.0
  buffer_size: 20000
  batch_size: 128
  num_workers: 4
  pin_memory: False
